#!/usr/bin/env bash
# Transfers a file from our client to a server
# Accepts 4 parameters:
# - The path to the file to be transferred
# - The IP of the server we want to transfer the file to
# - The username scp connects with
# - The path to the SSH private key that scp uses
# Displays Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY if less than 4 parameters are passed
# scp must transfer the file to the user's home directory ~/
# Strict host key checking must be disabled when using scp

if [ $# -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
else
    scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
fi

