#!/usr/bin/env bash
# Creates an RSA SSH key pair

# Ensure we are in the correct directory for storing keys
cd ~/.ssh || exit

# Generate the SSH key pair
ssh-keygen -t rsa -b 4096 -f school -N "betty"

# Display success message
echo "SSH key pair successfully generated."
echo "Private key: ~/.ssh/school"
echo "Public key: ~/.ssh/school.pub"
